import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [fontSize, setFontSize] = useState(16);
  const [text, setText] = useState("Hello World");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center my-5 h-screen w-full">
        <div className="w-4/5 h-4/5 border-2 border-solid border-red-500 p-5 text-xl tracking-wide">
          {text}
        </div>

        <div className="w-4/5 h-1/5"></div>
      </main>
    </div>
  );
}
